added docker command

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -48,19 +48,20 @@ jobs:
             --targets "Key=instanceids, Values=i-0c7db12f9e56a0269,i-030ee0c0b26ad7e7d" \
             --comment "Pull Docker image and run it" \
             --parameters commands='[
-              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}"
+              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
+              "docker pull ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.AWS_ECR_REPO}}:latest",
+              "docker run --rm -d -p 3000:3000 --name api ${{ steps.login-aws-ecr.outputs.registry }}/${{secrets.AWS_ECR_REPO}}:latest"
               ]' --query "Command.CommandId" --output text) 
 
           aws ssm wait command-executed \
           --command-id $command_id \
-          --instance-id i-0c7db12f9e56a0269
+          --instance-id i-0c7db12f9e56a0269 || true
 
           status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
 
           if [ $status == "Success" ]; then
             echo "Command executed sucessfully"
           else
-            echo "Command failed"
-            echo "Error: $status"
+            echo "Command failed - start debug"
             exit 1
           fi
