Added echo of error and exit if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -64,4 +64,6 @@ jobs:
             echo "Command executed sucessfully"
           else
             echo "Command failed"
+            echo "Error: $status"
+            exit 1
           fi
